version: '3'

secrets:
  secret_ssl_key_file:
    file: ssl/key.pem

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: always

  jaeger-ui-nginx-proxy:
    image: nginx:alpine
    restart: always
    ports:
      - "16686:443"
    volumes:
      - ./etc/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx-htpasswd:/etc/nginx/htpasswd
      - ./ssl:/etc/ssl
    depends_on:
      - jaeger

  otel-collector-gateway:
    image: otel/opentelemetry-collector-contrib:latest
    restart: always
# Disable port because otel-collector-edge is now entrypoint for tracing
#    ports:
#      - "4317:4317"   # OTLP gRPC receiver over HTTP/2
#      - "4318:4318"   # OTLP gRPC receiver over HTTP/1.1
    command: ["--config=/etc/otel-collector-gateway-config.yaml"]
    env_file:
      - secrets/otel-collector-gateway.env
      - ssl/.env
    volumes:
      - ./etc/otel-collector-gateway-config.yaml:/etc/otel-collector-gateway-config.yaml
      - ./etc/otel-collector-gateway-htpasswd:/etc/otel-collector-gateway-htpasswd
      - ./ssl:/etc/ssl
    secrets:
      - secret_ssl_key_file
    depends_on:
      - jaeger

  otel-collector-sidecar:
    image: otel/opentelemetry-collector-contrib:latest
    restart: always
    env_file:
      - secrets/otel-collector-sidecar.env
      - ssl/.env
    ports:
      - "4317:4317"   # OTLP gRPC receiver over HTTP/2
      - "4318:4318"   # OTLP gRPC receiver over HTTP/1.1
    command: ["--config=/etc/otel-collector-sidecar-config.yaml"]
    volumes:
      - ./etc/otel-collector-sidecar-config.yaml:/etc/otel-collector-sidecar-config.yaml
      - ./ssl:/etc/ssl
    secrets:
      - secret_ssl_key_file
    depends_on:
      - otel-collector-gateway
