extensions:
  health_check:
  basicauth/client:
    client_auth:
      username: ${env:COLLECTOR_GATEWAY_USER}
      password: ${env:COLLECTOR_GATEWAY_PASSWORD}
  bearertokenauth:
    token: ${env:COLLECTOR_GATEWAY_TOKEN}

receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlp/withBearerAuth:
    endpoint: otel-collector-gateway:4317
    auth:
      authenticator: bearertokenauth
    tls:
      cert_file: /etc/ssl/cert.pem
      key_file: /etc/ssl/key.pem
      # FIXME: Never ever do this in production. It's here only to simplify education.
      insecure_skip_verify: true # Don't verify certificate because it's self-signed

  otlp/withBasicAuth:
    endpoint: otel-collector-gateway:4317
    auth:
      authenticator: basicauth/client
    tls:
      cert_file: /etc/ssl/cert.pem
      key_file: /etc/ssl/key.pem
      # FIXME: Never ever do this in production. It's here only to simplify education.
      insecure_skip_verify: true # Don't verify certificate because it's self-signed

processors:
  batch:

service:
  extensions: [basicauth/client, bearertokenauth]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/withBearerAuth]
