extensions:
  health_check:
  basicauth/server:
    htpasswd:
      file: /etc/otel-collector-gateway-htpasswd
  bearertokenauth:
    token: ${env:COLLECTOR_GATEWAY_TOKEN}

receivers:
  otlp/withBearerAuth:
    protocols:
      grpc:
        tls:
          cert_file: /etc/ssl/cert.pem
          key_file: /etc/ssl/key.pem
        auth:
          authenticator: bearertokenauth
      http:
        tls:
          cert_file: /etc/ssl/cert.pem
          key_file: /etc/ssl/key.pem
        auth:
          authenticator: bearertokenauth

  otlp/withBasicAuth:
    protocols:
      grpc:
        tls:
          cert_file: /etc/ssl/cert.pem
          key_file: /etc/ssl/key.pem
        auth:
          authenticator: basicauth/server
      http:
        tls:
          cert_file: /etc/ssl/cert.pem
          key_file: /etc/ssl/key.pem
        auth:
          authenticator: basicauth/server

exporters:
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true

processors:
  batch:

service:
  extensions: [basicauth/server, bearertokenauth]
  pipelines:
    traces:
      receivers: [otlp/withBasicAuth]
      processors: [batch]
      exporters: [otlp]
