version: '3'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: always

  jaeger-ui-nginx-proxy:
    image: nginx:alpine
    restart: always
    ports:
      - "16686:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-htpasswd:/etc/nginx/htpasswd
    depends_on:
      - jaeger

  otel-collector-gateway:
    image: otel/opentelemetry-collector-contrib:latest
    restart: always
# Disable port because otel-collector-edge is now entrypoint for tracing
#    ports:
#      - "4317:4317"   # OTLP gRPC receiver
#      - "4318:4318"   # OTLP gRPC receiver via HTTP
#      - "13133:13133" # health_check extension
    command: ["--config=/etc/otel-collector-gateway-config.yaml"]
    volumes:
      - ./otel-collector-gateway-config.yaml:/etc/otel-collector-gateway-config.yaml
      - ./otel-collector-gateway-htpasswd:/etc/otel-collector-gateway-htpasswd
      - ./ssl:/etc/ssl
    depends_on:
      - jaeger

  otel-collector-edge:
    image: otel/opentelemetry-collector-contrib:latest
    restart: always
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP gRPC receiver via HTTP
      - "13133:13133" # health_check extension
    command: ["--config=/etc/otel-collector-edge-config.yaml"]
    volumes:
      - ./otel-collector-edge-config.yaml:/etc/otel-collector-edge-config.yaml
      - ./ssl:/etc/ssl
