version: '3'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    networks:
      - jaeger-net

  otel-collector:
    image: otel/opentelemetry-collector:latest
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP gRPC via HTTP
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    networks:
      - jaeger-net
    depends_on:
      - jaeger

  nginx-proxy:
    image: nginx:alpine
    ports:
      - "16686:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./htpasswd:/etc/nginx/htpasswd
    depends_on:
      - jaeger
    networks:
      - jaeger-net

networks:
  jaeger-net:
    driver: bridge
