extensions:
  health_check:
  basicauth/server:
    htpasswd:
      file: /etc/otel-collector-gateway-htpasswd

receivers:
  otlp:
    protocols:
      grpc:
        tls:
          cert_file: /etc/ssl/cert.pem
          key_file: /etc/ssl/key.pem

#        auth:
#          authenticator: basicauth/server
      http:
        tls:
          cert_file: /etc/ssl/cert.pem
          key_file: /etc/ssl/key.pem

#        auth:
#          authenticator: basicauth/server

exporters:
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true

processors:
  batch:

service:
  extensions: [basicauth/server]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
