extensions:
  health_check:
  basicauth/client:
    client_auth:
      username: username
      password: password

receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlp:
    endpoint: otel-collector-gateway:4317
#    auth:
#      authenticator: basicauth/client
    tls:
      insecure: true

processors:
  batch:

service:
  extensions: [basicauth/client]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
