extensions:
  health_check:
  basicauth/server:
    htpasswd:
      file: /etc/otel-collector-htpasswd

receivers:
  otlp:
    protocols:
      grpc:
        auth:
          authenticator: basicauth/server
      http:
        auth:
          authenticator: basicauth/server

exporters:
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true

processors:
  batch:

service:
  extensions: [basicauth/server]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
