version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: always
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
    command:
      # https://github.com/jaegertracing/jaeger/issues/1051
      # This was an attempt to solve memory overload when loading giant traces from storage,
      # but unfortunately it won't help. Looks like it only affects pagination.
      - "--es.max-doc-count=1000"
    depends_on:
      - elasticsearch

  jaeger-ui-nginx-proxy:
    image: nginx:alpine
    restart: always
    ports:
      - "16686:443"
    volumes:
      - ./etc/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx-htpasswd:/etc/nginx/htpasswd
      - ../ssl:/etc/ssl
    depends_on:
      - jaeger

  otel-collector-gateway:
    image: otel/opentelemetry-collector-contrib:latest
    restart: always
# Disable port because otel-collector-edge is now entrypoint for tracing
#    ports:
#      - "4317:4317"   # OTLP gRPC receiver over HTTP/2
#      - "4318:4318"   # OTLP gRPC receiver over HTTP/1.1
    command: ["--config=/etc/otel-collector-gateway-config.yaml"]
    env_file:
      - secrets/otel-collector-gateway.env
      - ../ssl/.env
    volumes:
      - ./etc/otel-collector-gateway-config.yaml:/etc/otel-collector-gateway-config.yaml
      - ./etc/otel-collector-gateway-htpasswd:/etc/otel-collector-gateway-htpasswd
      - ../ssl:/etc/ssl
    depends_on:
      - jaeger

  otel-collector-sidecar:
    image: otel/opentelemetry-collector-contrib:latest
    restart: always
    env_file:
      - secrets/otel-collector-sidecar.env
      - ../ssl/.env
    ports:
      - "4317:4317"   # OTLP gRPC receiver over HTTP/2
      - "4318:4318"   # OTLP gRPC receiver over HTTP/1.1
    command: ["--config=/etc/otel-collector-sidecar-config.yaml"]
    volumes:
      - ./etc/otel-collector-sidecar-config.yaml:/etc/otel-collector-sidecar-config.yaml
    depends_on:
      - otel-collector-gateway
