extensions:
  health_check:

receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
  otlp/jaeger:
{{ range nomadService "jaeger-backend-gRPC2" }}
    endpoint: {{ .Address }}:{{ .Port }}
{{ end }}
    tls:
      insecure: true

processors:
  batch:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp/jaeger]
