extensions:
  health_check:
  basicauth/client:
    # FIXME: store it in Vault
    client_auth:
      username: otel-collector-edge
      password: adidas

receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
  otlp:
    auth:
      authenticator: basicauth/client
    tls:
      # FIXME: Never ever do this in production. It's here only to simplify education.
      insecure_skip_verify: true # Don't verify certificate because it's self-signed
{{ range nomadService "otel-collector-gateway-gRPC2" }}
    endpoint: {{ .Address }}:{{ .Port }}
{{ end }}

processors:
  batch:

service:
  extensions: [basicauth/client]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, logging]
