extensions:
  health_check:
  basicauth/client:
    client_auth:
      username: "{{ with secret "kv/data/otel-collector-gateway/auth" }}{{ .Data.data.user }}{{ end }}"
      password: "{{ with secret "kv/data/otel-collector-gateway/auth" }}{{ .Data.data.password }}{{ end }}"

receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
  otlp:
    auth:
      authenticator: basicauth/client
    tls:
      # FIXME: Never ever do this in production. It's here only to simplify education.
      insecure_skip_verify: true # Don't verify certificate because it's self-signed
{{ range service "otel-collector-gateway-gRPC2" }}
    endpoint: {{ .Address }}:{{ .Port }}
{{ end }}

processors:
  batch:

service:
  extensions: [basicauth/client]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, logging]
