receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
  otlp:
    tls:
      insecure: true
{{ range nomadService "otel-collector-gateway-gRPC2" }}
    endpoint: {{ .Address }}:{{ .Port }}
{{ end }}

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, logging]
