extensions:
  health_check:
  basicauth/server:
    htpasswd:
      file: /etc/otel-collector-gateway-htpasswd

receivers:
  otlp/basicAuth:
    protocols:
      grpc:
        tls:
          cert_file: /etc/ssl/cert.pem
          key_file: /etc/ssl/key.pem
        auth:
          authenticator: basicauth/server

      http:
        tls:
          cert_file: /etc/ssl/cert.pem
          key_file: /etc/ssl/key.pem
        auth:
          authenticator: basicauth/server

exporters:
  logging:
  otlp/jaeger:
    endpoint: {{ env "NOMAD_ADDR_gRPC2" }}
    tls:
      insecure: true

processors:
  batch:

service:
  extensions: [health_check, basicauth/server]
  pipelines:
    traces:
      receivers: [otlp/basicAuth]
      processors: [batch]
      exporters: [logging, otlp/jaeger]
