receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
  otlp:
    tls:
      # FIXME: Never ever do this in production. It's here only to simplify education.
      insecure_skip_verify: true # Don't verify certificate because it's self-signed
{{ range nomadService "otel-collector-gateway-gRPC2" }}
    endpoint: {{ .Address }}:{{ .Port }}
{{ end }}

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, logging]
