extensions:
  health_check:
  bearertokenauth:
    token: "{{ with secret "kv/data/otel-collector-gateway/auth" }}{{ .Data.data.token }}{{ end }}"

receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
  otlp:
    auth:
      authenticator: bearertokenauth
    tls:
      # FIXME: Never ever do this in production. It's here only to simplify education.
      insecure_skip_verify: true # Don't verify certificate because it's self-signed
{{ range service "otel-collector-gateway-gRPC2" }}
    endpoint: {{ .Address }}:{{ .Port }}
{{ end }}

processors:
  batch:

service:
  extensions: [health_check, bearertokenauth]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, logging]
